[workspace]
members = [
  "iroh-mainline-content-discovery",
  "iroh-mainline-content-discovery-cli",
  "iroh-mainline-tracker",
  "tls",
]
resolver = "2"

[profile.release]
debug = true

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false


[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
unused-async = "warn"

[workspace.dependencies]
iroh = "0.30"
iroh-base = "0.30"
iroh-blobs = { version = "0.30", features = ["rpc"] }

[patch.crates-io]
iroh = { git = "https://github.com/n0-computer/iroh.git", branch = "iroh-0-31-0" }
iroh-base = { git = "https://github.com/n0-computer/iroh.git", branch = "iroh-0-31-0" }
iroh-blobs = { git = "https://github.com/n0-computer/iroh-blobs.git", branch = "iroh-0-31-0" }
